version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
    - mongodemo
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    - MONGO_INITDB_ROOT_USERNAME=mongodb
    - MONGO_INITDB_ROOT_PASSWORD=mongodb
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  mongodemo: